AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'test/channels/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false